### ISSUE TITLE
Request: Hide the terminal window?

### ISSUE THREAD

**Issue by sleepingdragoninn** [iranrmrf/NVHR#3]
The terminal window that NVHR runs in clearly shows its installed, but with the [FNV Performance Guide](https://wallsogb.github.io/FalloutNV-Performance-Guide/) now recommending flip windowed mode, It'd be helpful to be able to have NVHR run without a window so that it's not able to be alt-tabbed into.

Pretty low priority, but it's a nice-to-have if it's possible.

Currently using [RBTray](https://rbtray.sourceforge.net/) to work around this which works nicely - in case anyone else has the same thought.

**Comment by dlpnd** [comment]
Its already a feature...
![image](https://github.com/iranrmrf/Heap-Replacer/assets/11916166/2d1d82cd-46b6-42b6-809c-776bf3e8cb58)
